### PR TITLE
Dockerize local build & server and prepare for Kubernetes deployment

### PR DESCRIPTION
**Pull request by jeanpaulgalea**
This should simplify local development.

It will also make it possible to deploy the project on production using Kubernetes.

### CODE REVIEW

**Comment by jeanpaulgalea** [comment]
Thanks @nevun. Can confirm that `make build` and `make httpd` still works, as well as building Dockerfile.prod.

**Comment by xalgorithm** [comment]
I was able to get this to run on my local mac, but I had to pull out https://github.com/Yubico/developers.yubico.com/blob/60d502b559324229c709efcbc6abda691c217a95/Dockerfile.build#L30 line 30.  It admonished me that `group guid 20 already exists`

**Comment by jeanpaulgalea** [comment]
https://github.com/Yubico/developers.yubico.com/commit/d9d33992d94e7daae86686c585b8819624747915 should fix your issue.

**Comment by jeanpaulgalea** [comment]
https://github.com/Yubico/developers.yubico.com/commit/5e0d59fc83030733b92b1cb4204e93902ce3fdd5 attempts to add clarity.

**Pull request merged**
