### PR TITLE
Update SSH/GPG article for Windows

### PR DESCRIPTION
**Pull request by FFincannon**
https://yubico.atlassian.net/browse/DOC-271 up to step 3 of git config

### CODE REVIEW

**Comment by FFincannon** [comment]
@sebastianelfors , please review (taking into account my remarks in Slack) and if this is okay, please ask someone with the right permissions to merge this PR.

**Comment by sebastianelfors** [comment]
Review comments:

Under "Accessing via GPG4Win, Step 5", there is a double-space at this line: "instructions for doing  this configuration for GitHub are provided in "Configuring Git" below."

Under "Accessing via GPG4Win, Step 2", there is a list where all numbers are labeled as "1". This list should be changed to bullets or be removed.

I'd recommend a change of:
"If the GPG key is not yet configured, upload it to GitHub as described in GitHub's instructions,
link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account[Adding a New GPG Key to Your GitHub Account]." 
to this:
"If the GPG key is not yet configured, link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account[upload it to GitHub]."

**Review by sebastianelfors — COMMENTED** [review]
Under "Accessing via GPG4Win, Step 5", there is a double-space at this line: "instructions for doing  this configuration for GitHub are provided in "Configuring Git" below."

Under "Accessing via GPG4Win, Step 2", there is a list where all numbers are labeled as "1". This list should be changed to bullets or be removed.

I'd recommend a change of:
"If the GPG key is not yet configured, upload it to GitHub as described in GitHub's instructions,
link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account[Adding a New GPG Key to Your GitHub Account]." 
to this:
"If the GPG key is not yet configured, link:https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account[upload it to GitHub]."

**Comment by sebastianelfors** [comment]
All changes look good to me. The article is ready to be merged and published.

**Comment by FFincannon** [comment]
@elukewalker , please merge

**Review by elukewalker — APPROVED** [review]

**Pull request merged**
